### ISSUE TITLE
Error: Please specify platform for 'ota' environment

### ISSUE THREAD

**Issue by Greust** [cyberman54/ESP32-Paxcounter#388] opened 2019-07-01 14:21 UTC
Hi,
first of all: thanks for your work!

I successfully use the Paxcounter on a TTGO 2.1 Board. 
Today i tried to use the new Version on a Heltec V2, but Visual Studio aswell as Atom end the Cleanup with the error:

ERROR: Please specify platform for 'ota' environment

Any idea how to fix this?

Thanks a lot!

**Comment by cyberman54** [comment] 2019-07-01 20:37
Please update to current version of respository. This should be fixed already.

**Comment by tobievii** [comment] 2019-07-09 11:14
its not , just compiled does not work

**Comment by cyberman54** [comment] 2019-07-09 11:58
@tobievii i can't reproduce this here, please state to be sure we have same base:
- which platformio version do you use (pio --version) 
- which #commit of master branch did you compile

**Comment by cyberman54** [comment] 2019-07-09 11:59
Reopened.

**Comment by cyberman54** [comment] 2019-07-15 17:54
Probably this issue is platformio v3.x related; meanwhile i got confirmations that the code compiles fine with platformio v4.x.

So please make sure you're using pio v4.x,  not 3.x.

If problem persist with pio v4.x, please reopen this issue and try to give some more context information. thanks.

**Closed by cyberman54** 2019-07-15 17:54 UTC
