### ISSUE TITLE
Heltec ESP32 LoRa V2 Display works not properly

### ISSUE THREAD

**Issue by DasNordlicht** [cyberman54/ESP32-Paxcounter#262] opened 2019-02-04 07:25 UTC
The display stays black, sometimes it works after a few reboots. 
There seems to be a problem with the I2C bus.

[I][lorawan.cpp:369] lora_stack_init(): Starting LMIC...
[W][esp32-hal-i2c.c:1411] i2cCheckLineState(): invalid state sda(4)=0, scl(15)=0
[E][esp32-hal-i2c.c:1426] i2cCheckLineState(): Bus Invalid State, TwoWire() Can't init sda=0, scl=0
[I][main.cpp:337] setup(): Features: LED OTA BLE BTN_PD LORA OUIFLT OLED PLAIN

**Comment by DasNordlicht** [comment] 2019-02-04 10:36
I use the last commit e7a416cd7a5350fe6f2882af3621a9ebbfae1611

**Comment by cyberman54** [comment] 2019-02-04 10:42
Could you re-test without that commit?
I saw it working on heltec v2 already before this commit, maybe the bug came in with it.

**Comment by DasNordlicht** [comment] 2019-02-04 11:07
Which version worked for you, how far should I go back?

**Comment by aapris** [comment] 2019-02-04 11:40
I found one TTGO v2 running `v1.6.971` in my bag, its display worked until I flashed it with `v1.7.11`, now it remains blank.

**Comment by cyberman54** [comment] 2019-02-04 15:31
@DasNordlicht @aapris Please update to latest [6b3a367 ](https://github.com/cyberman54/ESP32-Paxcounter/commit/6b3a367e68c60571460274163bf578267645fca8), there was a fix in i2c handling two days ago which should solve this issue.

Please check and report result here, thanks.

**Comment by DasNordlicht** [comment] 2019-02-04 18:16
Sorry also no Display :-(

This is the arduino-esp32 pins_arduino.h:
https://github.com/espressif/arduino-esp32/blob/master/variants/heltec_wifi_lora_32/pins_arduino.h
And this the Heltec V2 Version:
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/blob/master/esp32/variants/wifi_lora_32_V2/pins_arduino.h

--- Heltec ---
**static const uint8_t SDA = 21;
static const uint8_t SCL = 22;**
static const uint8_t RST_OLED = 16;
static const uint8_t SCL_OLED = 15;
static const uint8_t SDA_OLED = 4;

--- Arduino ESP32 --- 
**static const uint8_t SDA = 4;
static const uint8_t SCL = 15;**
static const uint8_t OLED_SCL = 15;
static const uint8_t OLED_SDA = 4;
static const uint8_t OLED_RST = 16;

How can I use the right definition?

**Comment by DasNordlicht** [comment] 2019-02-04 18:37
OK, the error has already been reported by Heltec
https://github.com/espressif/arduino-esp32/pull/2392

**Comment by cyberman54** [comment] 2019-02-04 18:49
@DasNordlicht Seems we found the bug, thanks. I updated the paxcounter hal file vor Heltec v2, it should work now without the patch in pins_arduino.h. I will leave this in, until Heltec's pull request was merged. If you try to recompile and reflash it should now work with your v2 board.

**Comment by aapris** [comment] 2019-02-04 18:51
Can you update also `src/hal/ttgov2.h` and possibly `src/hal/heltec.h` and `src/hal/ttgov1.h` since they may have the same bug:
```
// Pins for I2C interface of OLED Display
#define MY_OLED_SDA OLED_SDA
#define MY_OLED_SCL OLED_SCL
```

**Comment by aapris** [comment] 2019-02-04 19:04
I tried this in `src/hal/ttgov2.h`without luck:
```
#define MY_OLED_SDA (21)
#define MY_OLED_SCL (22)
```

**Comment by cyberman54** [comment] 2019-02-04 19:45
fixed the platformio.ini.

**Comment by cyberman54** [comment] 2019-02-04 19:51
updated heltec v1 hal file with explicit pin numbers.

**Comment by cyberman54** [comment] 2019-02-04 19:57
updated TTGOv1 and TTGOv2 hal files with explicit pin numbers.

**Comment by DasNordlicht** [comment] 2019-02-10 14:44
So the Display is working:

Pins for I2C interface of OLED Display
#define MY_OLED_SDA (4)
#define MY_OLED_SCL (15)
#define MY_OLED_RST (16)

And an 10KOhm Resistor between +5V and PIN4

**Comment by cyberman54** [comment] 2019-02-10 15:05
sure that you have a heltec v2 and not a v1?

**Comment by cyberman54** [comment] 2019-02-10 15:53
I tested the current code from repo (v1.7.2) with a heltec V1.
Works like a charm, pinouts for v1 are correct.

**Comment by cyberman54** [comment] 2019-02-11 22:57
@DasNordlicht Meanwhile i tested with a heltec V2. The current settings in the repo are correct, it works with Heltec V2 (SDA=21/SCL=22).

If your board runs on SDA=4/SCL=15, it probably is a V1, or there are V2s with different pinouts.
My V2 has a printed label "V2" alongside the U.FL connector. This label is not present on V1 boards.

**Comment by Parr0t** [comment] 2019-03-17 22:18
@cyberman54 I have the problem again now. can it be that with the new update again the header files are wrong? my display shows me nothing although i have the V2 board from Heltec :(

**Comment by cyberman54** [comment] 2019-03-17 23:52
@Parr0t Probably the low power switch of heltec v2 board causes the trouble.
I disabled it in `heltecv2.h` for now, please reload this file and build again.

**Comment by Parr0t** [comment] 2019-03-18 09:10
now there are unfortunately new errors in the channel definition. these were either initialized incorrectly or the method in battery.cpp cannot work with it because it was set to adc2.

**Comment by cyberman54** [comment] 2019-03-18 10:27
Yes, this is an ADC2 problem, the battery.cpp was designed for ADC1 only.
Until battery.cpp is improved by somebody (could you make PR for this?) i will disable battery voltage monitoring in Heltec v2 hal file to avoid errors.

**Comment by cyberman54** [comment] 2019-03-18 20:17
https://github.com/cyberman54/ESP32-Paxcounter/issues/321

**Comment by 4jandals** [comment] 2019-03-21 00:47
I've have two variations of "Heltec V2" boards which came from two different suppliers. Both have the antenna connection on the right of the board below the v2 label. However, the components on the board are very slightly different.

With one of these boards, the latest heltecv2.h configuration works great, but for the other I had to make some strange changes to get the oled working.... 

When I looked at the order of the parameters being passed to U8X8_SSD1306_128X64_NONAME_HW_I2C, they are in a different order to what I've used in other projects. Switching the config from `U8X8_SSD1306_128X64_NONAME_HW_I2C` to `U8X8_SSD1306_128X64_NONAME_SW_I2C` and swapping the order as follows got it working for me:

```
// Pins for I2C interface of OLED Display
#define MY_OLED_SDA (16)
#define MY_OLED_SCL (4)
#define MY_OLED_RST (15)
```

And with this configuration, it also continues to work on my other v2 board.

**Comment by 4jandals** [comment] 2019-03-21 01:17
Looks like HW and SW have different constructs which explains the order (https://github.com/olikraus/u8g2/issues/664). 

What I didn't explain in the last post is that the problem I had with the display was the "invalid state sda(4)=0, scl(15)=0" error message. Switching to SW version of the I2C constructor avoids the error.

**Comment by cyberman54** [comment] 2019-03-21 07:02
I won't switch from hardware to software i2c, since this has drawbacks. If the software i2c works but shows no i2c errors this does.not mean that there are no errors ob the i2c bus.

We need to check the root cause for this issue to solve it.

A common problem with shenzen hardware is, that there is a lack in change/version management and documentation.

This issue could point to different or missing pullup resistors on the i2c bus, or a display type which comes with a driver chip which uses different timings or has timing issues.

Do you have an oscilloscope or logic analyzer to check what's going ob the i2c bus? E.g. a Rigol 1054 can analyze i2c data.

**Comment by cyberman54** [comment] 2019-03-24 19:25
V1.7.4 re-tested with Heltec V2, no display issues. Closing this now.

**Closed by cyberman54** 2019-03-24 19:25 UTC
